---
title: "bycicle-first-attempt"
author: "Wikash Sewlal"
date: "31-8-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Read data
This is an attempt to read and summarize the data.

```{r}
setwd("~/Documenten/Google programme/course8/track1-project/R")
tmp <- read_csv("/home/wikash/Documenten/Google programme/course8/track1-project/raw-data/Divvy_Stations_Trips_2013/Divvy_Trips_2013.csv")

glimpse(tmp)
hist(tmp$tripduration)


library(tidyr)
tmp %>% group_by(from_station_id) %>% drop_na() %>% summarize(mean_td = mean(tripduration))

attach(tmp)
tmp %>% count(bikeid) %>%
				arrange(desc(n))
 
		

asdf <- tmp %>% filter(bikeid == 480)
tmp %>% filter(bikeid == 383) %>%
				group_by(from_station_id) %>%
				summarize(sumdur = sum(tripduration)) %>%
				arrange(desc(sumdur))
				
longest_stations <- tmp %>% group_by(from_station_id) %>%
				summarize(sumdur = sum(tripduration)) %>%
				arrange(desc(sumdur))

longest_stations[1:10,]
```

